<footer>
	<div class="pull-right">
		<a href="https://github.com/PepeEnthusiast/electrumx-dashboard-pepecoin">Pepecoin ElectrumX Dashboard v1.0.0</a> - © 2024
	</div>
	<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if ($this->section === "main") {
		$section = "";
	} else {
		$section = "?p=" . $this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");
</script>