<footer>
	<div class="pull-right">
		<a href="https://github.com/bachelor-emgi/electrumx-pep" target="_blank">Pepecoin ElectrumX Dashboard by Mr Bachelor emgi</a>
	</div>
	<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if ($this->section === "main") {
		$section = "";
	} else {
		$section = "?p=" . $this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");
</script>