<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="referrer" content="no-referrer">

  <title><?= $title ?> - ElectrumX Dashboard</title>

  <link href="assets/images/favicon.png" rel="shortcut icon" type="image/png">

  <!-- Bootstrap -->
  <link href="assets/css/bootstrap.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="assets/css/font-awesome.min.css" rel="stylesheet">
  <!-- Datatables -->
  <link href="assets/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="assets/css/buttons.bootstrap.min.css" rel="stylesheet">
  <!-- JQVMap -->
  <link href="assets/css/jqvmap.min.css" rel="stylesheet">
  <!-- Switchery -->
  <link href="assets/css/switchery.min.css" rel="stylesheet">

  <link href="assets/css/bootstrap-multiselect.css" rel="stylesheet">
  <!-- Custom Theme Style -->
  <link href="assets/css/custom.css" rel="stylesheet">
</head>

<div class="bottom_bar">
  <a href="?p=main" class="<?= ($this->section == "main") ? 'active' : ''; ?>">
    <i class="fa fa-home"></i>
    <span>Main</span>
  </a>
  <a href="?p=sessions" class="<?= ($this->section == "sessions") ? 'active' : ''; ?>">
    <i class="fa fa-user-o"></i>
    <span>Sessions</span>
  </a>
  <a href="?p=rules" class="<?= ($this->section == "rules") ? 'active' : ''; ?>">
    <i class="fa fa-shield"></i>
    <span>Rules</span>
  </a>
  <a href="?p=peers" class="<?= ($this->section == "peers") ? 'active' : ''; ?>">
    <i class="fa fa-server"></i>
    <span>Peers</span>
  </a>
  <a href="?p=about" class="<?= ($this->section == "about") ? 'active' : ''; ?>">
    <i class="fa fa-info"></i>
    <span>About</span>
  </a>
</div>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border-bottom: 1px solid transparent;">
            <a href="index.php" class="site_title"><img src="../assets/images/pepecoinlogo.svg"
                alt="Your Image Description" style="width: 24px; height: 24px;"> <span>ElectrumX Dash</span></a>
          </div>
          <div class="clearfix"></div>

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <ul class="nav side-menu">
                <!-- First item with rounded top corners -->
                <li class="menu-item rounded-top">
                  <a href="?p=main" <?php if ($this->section == "main")
                    echo 'class="active"'; ?>>
                    <i class="fa fa-home"></i> Main
                  </a>
                </li>
                <!-- Other items without margin or rounded corners -->
                <li class="menu-item">
                  <a href="?p=sessions" <?php if ($this->section == "sessions")
                    echo 'class="active"'; ?>>
                    <i class="fa fa-user-o"></i> Sessions
                  </a>
                </li>
                <li class="menu-item">
                  <a href="?p=rules" <?php if ($this->section == "rules")
                    echo 'class="active"'; ?>>
                    <i class="fa fa-shield"></i> Rules
                  </a>
                </li>
                <li class="menu-item">
                  <a href="?p=peers" <?php if ($this->section == "peers")
                    echo 'class="active"'; ?>>
                    <i class="fa fa-server"></i> Peers
                  </a>
                </li>
                <li class="menu-item rounded-bottom">
                  <a href="?p=about" <?php if ($this->section == "about")
                    echo 'class="active"'; ?>>
                    <i class="fa fa-info"></i> About
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <!-- /sidebar menu -->
        </div>

      </div>

      <!-- page content -->
      <div class="right_col" role="main" style="min-height:100%;">